### ISSUE TITLE
Panic when parsing polymorphic row type with field contracts

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#876]
**Describe the bug**

The following causes a panic in the parser:

```nickel
let x | forall r. { k | Num; r } = { k = 5, v = 10 } in
x
```

The backtrace is:

```
thread 'main' panicked at 'TermPos::unwrap', src/parser/uniterm.rs:302:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: nickel_lang::position::TermPos::unwrap
             at ./src/position.rs:97:30
   3: nickel_lang::parser::uniterm::<impl core::convert::TryFrom<nickel_lang::parser::uniterm::UniRecord> for nickel_lang::types::Types>::try_from::{{closure}}
             at ./src/parser/uniterm.rs:302:25
   4: core::result::Result<T,E>::map_err
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:855:27
   5: nickel_lang::parser::uniterm::<impl core::convert::TryFrom<nickel_lang::parser::uniterm::UniRecord> for nickel_lang::types::Types>::try_from
             at ./src/parser/uniterm.rs:297:13
   6: nickel_lang::parser::uniterm::<impl core::convert::TryFrom<nickel_lang::parser::uniterm::UniTerm> for nickel_lang::types::Types>::try_from
             at ./src/parser/uniterm.rs:76:39
   7: nickel_lang::parser::grammar::__action295
             at ./target/debug/build/nickel-lang-435f26e1a24f047b/out/parser/grammar.rs:37964:5
   8: nickel_lang::parser::grammar::__parse__Term::__reduce
             at ./target/debug/build/nickel-lang-435f26e1a24f047b/out/parser/grammar.rs:22760:34
   9: <nickel_lang::parser::grammar::__parse__Term::__StateMachine as lalrpop_util::state_machine::ParserDefinition>::reduce
             at ./target/debug/build/nickel-lang-435f26e1a24f047b/out/parser/grammar.rs:19504:13
  10: lalrpop_util::state_machine::Parser<D,I>::reduce
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:587:9
  11: lalrpop_util::state_machine::Parser<D,I>::parse
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:257:38
  12: lalrpop_util::state_machine::Parser<D,I>::drive
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:211:9
  13: nickel_lang::parser::grammar::__parse__Term::TermParser::parse
             at ./target/debug/build/nickel-lang-435f26e1a24f047b/out/parser/grammar.rs:22234:13
  14: nickel_lang::parser::<impl nickel_lang::parser::grammar::__parse__Term::TermParser>::parse_term_lax
             at ./src/parser/mod.rs:77:22
  15: nickel_lang::cache::Cache::parse_nocache_multi
             at ./src/cache.rs:450:21
  16: nickel_lang::cache::Cache::parse_nocache
             at ./src/cache.rs:435:9
  17: nickel_lang::cache::Cache::parse_lax
             at ./src/cache.rs:359:38
  18: nickel_lang::cache::Cache::parse
             at ./src/cache.rs:377:22
  19: nickel_lang::cache::Cache::prepare
             at ./src/cache.rs:682:35
  20: nickel_lang::program::Program::prepare_eval
             at ./src/program.rs:81:9
  21: nickel_lang::program::Program::eval_full
             at ./src/program.rs:99:32
  22: nickel::main
             at ./src/bin/nickel.rs:201:21
  23: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior**

The above code should fail to parse. As stated in [RFC002](https://github.com/tweag/nickel/blob/master/rfcs/002-merge-types-terms-syntax.md#records), row tails are only permitted following a syntactically valid record type. Since `{ k | Num }` is _not_ a syntactically valid record type, the above term is not permitted to have a tail, and users should ideally be informed of this.

**Environment**
 - OS name + version: NixOS
 - Version of the code: current `master`

**Comment by yannham** [comment]
This code should actually be rejected by the parser, cf [RFC002](https://github.com/tweag/nickel/blob/master/rfcs/002-merge-types-terms-syntax.md#records) (where to allow a tail section).

**Comment by matthew-healy** [comment]
@yannham Thanks for the clarification! I've updated the **Expected behaviour** section, so hopefully now it should be correct.
