### ISSUE TITLE
Panic in parser when misusing type variables

### ISSUE THREAD

**Issue by matthew-healy** [tweag/nickel#942]
**Describe the bug**

The following program causes a panic in the parser:

```
let f | forall r. { x: r; r } -> { x: r; r } = fun r => r in f { x = 1 }
```

The full error with backtrace is:

```
thread 'main' panicked at 'var kind mismatch: VarKindMismatch', src/parser/uniterm.rs:526:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1064:23
   4: <nickel_lang::types::RecordRows as nickel_lang::parser::uniterm::FixTypeVars>::fix_type_vars_env
             at ./src/parser/uniterm.rs:525:21
   5: <nickel_lang::types::RecordRows as nickel_lang::parser::uniterm::FixTypeVars>::fix_type_vars_env
             at ./src/parser/uniterm.rs:534:17
   6: <nickel_lang::types::Types as nickel_lang::parser::uniterm::FixTypeVars>::fix_type_vars_env
             at ./src/parser/uniterm.rs:511:45
   7: <nickel_lang::types::Types as nickel_lang::parser::uniterm::FixTypeVars>::fix_type_vars_env
             at ./src/parser/uniterm.rs:476:17
   8: <nickel_lang::types::Types as nickel_lang::parser::uniterm::FixTypeVars>::fix_type_vars_env
             at ./src/parser/uniterm.rs:502:17
   9: nickel_lang::parser::uniterm::FixTypeVars::fix_type_vars
             at ./src/parser/uniterm.rs:456:9
  10: nickel_lang::parser::grammar::__action5
             at ./target/debug/build/nickel-lang-b93f245fdd2c3a9e/out/parser/grammar.rs:34805:9
  11: nickel_lang::parser::grammar::__parse__ExtendedTerm::__reduce195
             at ./target/debug/build/nickel-lang-b93f245fdd2c3a9e/out/parser/grammar.rs:12290:20
  12: nickel_lang::parser::grammar::__parse__ExtendedTerm::__reduce
             at ./target/debug/build/nickel-lang-b93f245fdd2c3a9e/out/parser/grammar.rs:6812:17
  13: <nickel_lang::parser::grammar::__parse__ExtendedTerm::__StateMachine as lalrpop_util::state_machine::ParserDefinition>::reduce
             at ./target/debug/build/nickel-lang-b93f245fdd2c3a9e/out/parser/grammar.rs:3142:13
  14: lalrpop_util::state_machine::Parser<D,I>::reduce
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:587:9
  15: lalrpop_util::state_machine::Parser<D,I>::parse
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:257:38
  16: lalrpop_util::state_machine::Parser<D,I>::drive
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-util-0.19.8/src/state_machine.rs:211:9
  17: nickel_lang::parser::grammar::__parse__ExtendedTerm::ExtendedTermParser::parse
             at ./target/debug/build/nickel-lang-b93f245fdd2c3a9e/out/parser/grammar.rs:5999:13
  18: nickel_lang::parser::<impl nickel_lang::parser::grammar::__parse__ExtendedTerm::ExtendedTermParser>::parse_term_tolerant
             at ./src/parser/mod.rs:42:22
  19: nickel_lang::repl::InputParser::parse
             at ./src/repl/mod.rs:359:22
  20: <nickel_lang::repl::InputParser as rustyline::validate::Validator>::validate
             at ./src/repl/mod.rs:383:15
  21: rustyline::edit::State<H>::validate
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/edit.rs:220:26
  22: rustyline::command::execute
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/command.rs:128:37
  23: rustyline::readline_edit
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/lib.rs:537:15
  24: rustyline::readline_raw
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/lib.rs:572:22
  25: rustyline::Editor<H>::readline_with
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/lib.rs:784:13
  26: rustyline::Editor<H>::readline
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-9.1.2/src/lib.rs:760:9
  27: nickel_lang::repl::rustyline_frontend::repl
             at ./src/repl/rustyline_frontend.rs:42:20
  28: nickel::main
             at ./src/bin/nickel.rs:100:12
  29: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by matthew-healy** [comment]
Yeah, I noticed that the docs said there was an error but it just got missed :grin:
